services:

  postgres:
    image: postgres:15
    container_name: ecommerce-warehouse
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dataeng
      POSTGRES_PASSWORD: dataeng123
      POSTGRES_DB: retail_warehouse
    volumes:
      - ecommerce_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ecommerce_pgdata:
